version: '3.3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: bash -c "sleep 15 && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mysql
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=mysql
      - DB_NAME=ereputation
      - DB_USER=root
      - DB_PASSWORD=whatever..
      - DB_PORT=3306
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    stdin_open: true
    tty: true

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=whatever..
      - MYSQL_DATABASE=ereputation
      - MYSQL_USER=root
      - MYSQL_PASSWORD=whatever..
    volumes:
      - db:/var/lib/mysql